VTKU-28 : Downgrade buggy reflections
It caused a huge number of very strange
NoClassDefFoundErrors.

https://groups.google.com/forum/#!topic/dropwizard-user/I0K4e0APudY